steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'server/Dockerfile'
      - '-t'
      - 'asia-south1-docker.pkg.dev/sky-meet-01/video-generator/video-generator-backend:$COMMIT_SHA'
      - 'server'

  # 2. Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/sky-meet-01/video-generator/video-generator-backend:$COMMIT_SHA'

  # 3. Deploy the new image automatically to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'video-generator-backend'
      - '--image=asia-south1-docker.pkg.dev/sky-meet-01/video-generator/video-generator-backend:$COMMIT_SHA'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--port=5000'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=1200s'
      - '--concurrency=1'
      - '--min=0'
      - '--max=5'
      - '--cpu-boost'
      - '--service-account=video-generator-run@sky-meet-01.iam.gserviceaccount.com'
      - '--allow-unauthenticated'

images:
  - 'asia-south1-docker.pkg.dev/sky-meet-01/video-generator/video-generator-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY